# who said CC = tcc -mt -f- -ff- -w+ -O -Z -k- -d -b- -vi- -tDc \
# -IC:\tc\include /Lc:\tc\lib ...? That does not work out at all...
CC = tcc -mt -lt -f- -f87- -w -O -Z -k -Ic:\tc\include -Lc:\tc\lib

INC  = cluster.h dir16.h dirfind.h diskio.h dostypes.h drives.h fatio.h

OBJ = cluster.obj dir16.obj dirfind.obj diskio.obj drives.obj fatio.obj undelete.obj

all: $(OBJ)
        $(CC) -eundelete *.obj

$(OBJ): $(INC)

.c.obj:
	$(CC) -c $<
